[project]
name = "comfyui-xav-anima-style-selector"
version = "1.0.1"
description = "ComfyUI nodes for quick and easy style selection for the Anima model"
author = "XAV"
license = {text = "MIT"}
dependencies = []

[project.urls]
Repository = "https://github.com/XAV-Games/comfyui-xav-anima-style-selector"

[tool.comfy]
PublisherId = "xav"
DisplayName = "XAV Anima Style Selector"
Icon = "https://xav.su/favicon_io/android-chrome-512x512.png"